# Generated by Django 5.1.4 on 2026-07-10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="PolymarketMarket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("external_id", models.CharField(max_length=64, unique=True)),
                ("condition_id", models.CharField(db_index=True, max_length=128)),
                ("slug", models.CharField(blank=True, db_index=True, max_length=512)),
                ("question", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("active", models.BooleanField(db_index=True, null=True)),
                ("closed", models.BooleanField(db_index=True, null=True)),
                ("archived", models.BooleanField(db_index=True, null=True)),
                ("restricted", models.BooleanField(db_index=True, null=True)),
                ("accepting_orders", models.BooleanField(db_index=True, null=True)),
                ("market_created_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("market_updated_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, db_index=True, null=True)),
                (
                    "liquidity",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=12,
                        max_digits=32,
                        null=True,
                    ),
                ),
                (
                    "volume",
                    models.DecimalField(
                        blank=True,
                        db_index=True,
                        decimal_places=12,
                        max_digits=32,
                        null=True,
                    ),
                ),
                (
                    "liquidity_clob",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True),
                ),
                (
                    "volume_clob",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True),
                ),
                (
                    "volume_24hr",
                    models.DecimalField(blank=True, decimal_places=12, max_digits=32, null=True),
                ),
                ("clob_token_ids", models.JSONField(blank=True, default=list)),
                ("raw_payload", models.JSONField()),
                ("first_synced_at", models.DateTimeField(auto_now_add=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-market_created_at", "-external_id"],
                "indexes": [
                    models.Index(
                        fields=["closed", "-market_created_at"],
                        name="markets_pol_closed_b4155a_idx",
                    ),
                    models.Index(fields=["active", "closed"], name="markets_pol_active_7e641c_idx"),
                ],
            },
        ),
    ]
