# Generated by Django 5.1.4 on 2026-07-10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("markets", "0002_polymarketmarket_sync_prices"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="polymarketmarket",
            name="raw_payload",
        ),
    ]
